# Generated by Django 4.1.1 on 2022-12-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='traking_id',
            new_name='tracking_id',
        ),
    ]
