# Generated by Django 4.1.1 on 2022-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewmodel',
            name='session_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
