# Generated by Django 4.1.1 on 2023-03-25 08:56

from django.db import migrations, models
import django.db.models.deletion
import meta.models
import tour.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageId', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_pref', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email'), ('phone', 'phone')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('turkey', 'Turkey')], max_length=20)),
                ('city', models.CharField(choices=[('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('muğla', 'Muğla'), ('aydın', 'Aydın'), ('izmir', 'İzmir'), ('nevşehir', 'Nevşehir'), ('edirne', 'Edirne'), ('bursa', 'Bursa'), ('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('ankara', 'Ankara')], max_length=35, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to=tour.models.destination_thumb_path, validators=[tour.models.validate_image_size])),
                ('alttag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('seo_imagelink', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('durations', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to=tour.models.tour_thumbnail_path, validators=[tour.models.validate_image_size])),
                ('description', models.TextField()),
                ('accommodation', models.TextField()),
                ('transportation', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('destinations', models.ManyToManyField(to='tour.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=tour.models.tourimagedirectorypath, validators=[tour.models.validate_image_size])),
                ('alttag', models.CharField(max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='BookingExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_pref', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email'), ('phone', 'phone')], max_length=20)),
                ('arrival', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('adult', models.IntegerField(default=1)),
                ('child', models.IntegerField(blank=True, null=True)),
                ('transportation', models.CharField(choices=[('taxi', 'Taxi'), ('private_car', 'Private Car'), ('vip_tour', 'VIP Tour')], max_length=50)),
                ('accommodation', models.CharField(choices=[('5-star', '5-Star'), ('4-star', '4-Star'), ('3-star', '3-Star'), ('airbnb', 'Airbnb')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinations', models.ManyToManyField(to='tour.destination')),
            ],
        ),
    ]
