# Generated by Django 4.1.1 on 2022-12-02 07:05

from django.db import migrations, models
import django.db.models.deletion
import tour.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=tour.models.destination_thumb_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD'), ('TL', 'TL'), ('EUR', 'EUR')], default='BDT', max_length=20)),
                ('discount', models.PositiveIntegerField()),
                ('durations', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=1)),
                ('accommodation', models.TextField()),
                ('transportation', models.TextField()),
                ('overview', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('meta', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('destinations', models.ManyToManyField(to='tour.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=tour.models.tourimagedirectorypath)),
                ('altText', models.CharField(max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
