# Generated by Django 4.1.1 on 2022-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
