# Generated by Django 4.1.1 on 2022-12-02 07:42

from django.db import migrations, models
import tour.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=tour.models.destination_thumb_path),
        ),
    ]
