# Generated by Django 4.1.1 on 2022-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
