# Generated by Django 4.1.1 on 2023-04-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tourimage_alttag_alter_tourimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
