# Generated by Django 4.1.1 on 2022-12-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_alttext_tourimage_alttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='imagelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
