# Generated by Django 4.1.1 on 2022-12-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_destination_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, choices=[('turkey', 'turkey')], max_length=20, null=True),
        ),
    ]
