# Generated by Django 4.1.1 on 2022-12-16 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='last_modified',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 12, 16, 21, 53, 58, 980485, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
