# Generated by Django 4.1.1 on 2022-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
