# Generated by Django 4.1.1 on 2022-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('konya', 'Konya'), ('bursa', 'Bursa'), ('ankara', 'Ankara'), ('aydın', 'Aydın'), ('edirne', 'Edirne'), ('izmir', 'İzmir'), ('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('muğla', 'Muğla'), ('sanlıurfa', 'Şanlıurfa'), ('nevşehir', 'Nevşehir')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, default='turkey', max_length=20, null=True),
        ),
    ]
