# Generated by Django 4.1.1 on 2022-12-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
