# Generated by Django 4.1.1 on 2022-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_destination_city_alter_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('aydın', 'Aydın'), ('edirne', 'Edirne'), ('bursa', 'Bursa'), ('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('izmir', 'İzmir'), ('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('muğla', 'Muğla'), ('nevşehir', 'Nevşehir'), ('ankara', 'Ankara')], max_length=30, null=True, unique=True),
        ),
    ]
