# Generated by Django 4.1.1 on 2022-10-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
    ]
