# Generated by Django 4.1.1 on 2022-10-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_remove_destination_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tourtype',
        ),
    ]
