# Generated by Django 4.1.1 on 2022-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('bursa', 'Bursa'), ('sanlıurfa', 'Şanlıurfa'), ('muğla', 'Muğla'), ('aydın', 'Aydın'), ('nevşehir', 'Nevşehir'), ('konya', 'Konya'), ('edirne', 'Edirne'), ('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('ankara', 'Ankara'), ('izmir', 'İzmir')], max_length=30, null=True, unique=True),
        ),
    ]
