# Generated by Django 4.1.1 on 2023-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tour_created_at_alter_tour_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='size',
            new_name='max_size',
        ),
        migrations.AddField(
            model_name='tour',
            name='min_size',
            field=models.IntegerField(default=1),
        ),
    ]
