# Generated by Django 4.1.1 on 2023-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_rename_size_tour_max_size_tour_min_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pacakgeId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
