# Generated by Django 4.1.1 on 2022-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_remove_tour_tourtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
