# Generated by Django 4.1.1 on 2022-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('antalya', 'Antalya'), ('konya', 'Konya'), ('muğla', 'Muğla'), ('nevşehir', 'Nevşehir'), ('bursa', 'Bursa'), ('aydın', 'Aydın'), ('edirne', 'Edirne'), ('ankara', 'Ankara'), ('istanbul', 'Istanbul'), ('sanlıurfa', 'Şanlıurfa'), ('izmir', 'İzmir')], max_length=30, null=True, unique=True),
        ),
    ]
