# Generated by Django 4.1.1 on 2023-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_booking_pacakgeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pacakgeId',
            new_name='packageId',
        ),
    ]
