# Generated by Django 4.1.1 on 2022-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_tour_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourimage',
            name='altText',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
