# Generated by Django 4.1.1 on 2022-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('istanbul', 'Istanbul'), ('bursa', 'Bursa'), ('antalya', 'Antalya'), ('edirne', 'Edirne'), ('konya', 'Konya'), ('izmir', 'İzmir'), ('muğla', 'Muğla'), ('aydın', 'Aydın'), ('sanlıurfa', 'Şanlıurfa'), ('nevşehir', 'Nevşehir'), ('ankara', 'Ankara')], max_length=30, null=True, unique=True),
        ),
    ]
