# Generated by Django 4.1.1 on 2022-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tourimage_alttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
