# Generated by Django 4.1.1 on 2022-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_destination_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_pref', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email'), ('phone', 'phone')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('nevşehir', 'Nevşehir'), ('izmir', 'İzmir'), ('istanbul', 'Istanbul'), ('ankara', 'Ankara'), ('aydın', 'Aydın'), ('konya', 'Konya'), ('edirne', 'Edirne'), ('antalya', 'Antalya'), ('muğla', 'Muğla'), ('bursa', 'Bursa'), ('sanlıurfa', 'Şanlıurfa')], max_length=30, null=True, unique=True),
        ),
    ]
