# Generated by Django 4.1.1 on 2022-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_booking_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('antalya', 'Antalya'), ('izmir', 'İzmir'), ('nevşehir', 'Nevşehir'), ('ankara', 'Ankara'), ('aydın', 'Aydın'), ('bursa', 'Bursa'), ('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('edirne', 'Edirne'), ('istanbul', 'Istanbul'), ('muğla', 'Muğla')], max_length=30, null=True, unique=True),
        ),
    ]
