# Generated by Django 4.1.1 on 2023-02-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_bookingextended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingextended',
            old_name='group_size',
            new_name='no_of_persons',
        ),
    ]
