# Generated by Django 4.1.1 on 2022-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
