# Generated by Django 4.1.1 on 2022-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('aydın', 'Aydın'), ('istanbul', 'Istanbul'), ('ankara', 'Ankara'), ('nevşehir', 'Nevşehir'), ('bursa', 'Bursa'), ('edirne', 'Edirne'), ('izmir', 'İzmir'), ('antalya', 'Antalya'), ('muğla', 'Muğla')], max_length=30, null=True, unique=True),
        ),
    ]
