# Generated by Django 4.1.1 on 2022-11-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
