# Generated by Django 4.1.1 on 2022-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('nevşehir', 'Nevşehir'), ('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('bursa', 'Bursa'), ('izmir', 'İzmir'), ('konya', 'Konya'), ('aydın', 'Aydın'), ('ankara', 'Ankara'), ('edirne', 'Edirne'), ('sanlıurfa', 'Şanlıurfa'), ('muğla', 'Muğla')], max_length=30, null=True, unique=True),
        ),
    ]
