# Generated by Django 4.1.1 on 2022-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('aydın', 'Aydın'), ('istanbul', 'Istanbul'), ('izmir', 'İzmir'), ('bursa', 'Bursa'), ('antalya', 'Antalya'), ('ankara', 'Ankara'), ('sanlıurfa', 'Şanlıurfa'), ('muğla', 'Muğla'), ('nevşehir', 'Nevşehir'), ('konya', 'Konya'), ('edirne', 'Edirne')], max_length=30, null=True, unique=True),
        ),
    ]
