# Generated by Django 4.1.1 on 2022-11-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='continent',
        ),
    ]
