# Generated by Django 4.1.1 on 2022-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('ankara', 'Ankara'), ('edirne', 'Edirne'), ('antalya', 'Antalya'), ('nevşehir', 'Nevşehir'), ('bursa', 'Bursa'), ('sanlıurfa', 'Şanlıurfa'), ('muğla', 'Muğla'), ('istanbul', 'Istanbul'), ('aydın', 'Aydın'), ('konya', 'Konya'), ('izmir', 'İzmir')], max_length=30, null=True, unique=True),
        ),
    ]
