# Generated by Django 4.1.1 on 2022-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('antalya', 'Antalya'), ('bursa', 'Bursa'), ('aydın', 'Aydın'), ('edirne', 'Edirne'), ('izmir', 'İzmir'), ('muğla', 'Muğla'), ('nevşehir', 'Nevşehir'), ('konya', 'Konya'), ('ankara', 'Ankara'), ('istanbul', 'Istanbul'), ('sanlıurfa', 'Şanlıurfa')], max_length=30, null=True, unique=True),
        ),
    ]
