# Generated by Django 4.1.1 on 2022-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('ankara', 'Ankara'), ('bursa', 'Bursa'), ('aydın', 'Aydın'), ('nevşehir', 'Nevşehir'), ('edirne', 'Edirne'), ('izmir', 'İzmir'), ('antalya', 'Antalya'), ('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('muğla', 'Muğla'), ('istanbul', 'Istanbul')], max_length=30, null=True, unique=True),
        ),
    ]
