# Generated by Django 4.1.1 on 2022-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_alter_destination_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, choices=[('aydın', 'Aydın'), ('nevşehir', 'Nevşehir'), ('sanlıurfa', 'Şanlıurfa'), ('antalya', 'Antalya'), ('edirne', 'Edirne'), ('istanbul', 'Istanbul'), ('muğla', 'Muğla'), ('izmir', 'İzmir'), ('bursa', 'Bursa'), ('konya', 'Konya'), ('ankara', 'Ankara')], max_length=30, null=True, unique=True),
        ),
    ]
