# Generated by Django 4.1.1 on 2023-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(blank=True, default='Ottoman travels, Tourism in Turkey, Private Tourism in Turkiye, Best Tourism in Turkey, Tours and Travels, Tour Guide in Istanbul, Trip to Istanbul, Visit in Turkey, Tourist Attractions in Istanbul, Medical Tourism, Tourist Places in Turkey, Travel and Tourism, Tourist Spot, Adventure Tourism, Tourist Destination, Private Tour Package in Istanbul, Best Tourist places in the world, Cheap Tour Package in Turkey', null=True),
        ),
    ]
