# Generated by Django 4.1.1 on 2023-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
