# Generated by Django 4.1.1 on 2022-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_homebanner_tour_populardest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('contact', 'contact'), ('tour', 'tour'), ('blog', 'blog')], max_length=25, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('imagelink', models.URLField()),
            ],
        ),
    ]
