# Generated by Django 4.1.1 on 2022-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='imagelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
