# Generated by Django 4.1.1 on 2022-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_socialmedia_email_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
