# Generated by Django 4.1.1 on 2022-12-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_socialmedia_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='google_map',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
