# Generated by Django 4.1.1 on 2022-12-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_socialmedia_address_alter_socialmedia_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
