# Generated by Django 4.1.1 on 2022-12-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='imagecaption',
            new_name='alttag',
        ),
    ]
