# Generated by Django 4.1.1 on 2022-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_alttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
