# Generated by Django 4.1.1 on 2023-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorybangla_alter_banglablog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybangla',
            options={'ordering': ['-id'], 'verbose_name': 'categorybangla', 'verbose_name_plural': 'categoriesbangla'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='eng_blog_url',
            new_name='ban_blog_url',
        ),
        migrations.AddField(
            model_name='banglablog',
            name='eng_blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
