# Generated by Django 4.1.1 on 2023-05-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_eng_blog_url_banglablog_ref_blog_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ref_blog_url',
        ),
        migrations.AlterField(
            model_name='banglablog',
            name='ref_blog_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
