# Generated by Django 4.1.1 on 2023-05-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_ref_blog_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banglablog',
            old_name='ref_blog_url',
            new_name='ref_blog',
        ),
    ]
