# Generated by Django 4.1.1 on 2022-10-06 20:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to=blog.models.post_directory_path),
        ),
    ]
