# Generated by Django 4.1.1 on 2022-10-15 15:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='imagecaption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to=blog.models.post_path),
        ),
    ]
