# Generated by Django 4.1.1 on 2022-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
