# Generated by Django 4.1.1 on 2022-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_category_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
