# Generated by Django 4.1.1 on 2022-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_tag_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
