# Generated by Django 4.1.1 on 2022-12-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_tag_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
