# Generated by Django 4.1.1 on 2022-12-14 10:07

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to=mainapp.models.bannerdirectory)),
                ('alttag', models.CharField(max_length=100)),
            ],
        ),
    ]
