# Generated by Django 4.1.1 on 2022-12-14 10:07

from django.db import migrations, models
import django.db.models.deletion
import tour.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_pref', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email'), ('phone', 'phone')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('turkey', 'turkey')], max_length=20)),
                ('city', models.CharField(choices=[('istanbul', 'Istanbul'), ('antalya', 'Antalya'), ('muğla', 'Muğla'), ('aydın', 'Aydın'), ('izmir', 'İzmir'), ('nevşehir', 'Nevşehir'), ('edirne', 'Edirne'), ('bursa', 'Bursa'), ('konya', 'Konya'), ('sanlıurfa', 'Şanlıurfa'), ('ankara', 'Ankara')], max_length=35, unique=True)),
                ('thumbnail', models.ImageField(upload_to=tour.models.destination_thumb_path)),
                ('alttag', models.CharField(max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD'), ('TL', 'TL'), ('EUR', 'EUR')], default='BDT', max_length=20)),
                ('discount', models.PositiveIntegerField()),
                ('durations', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=1)),
                ('accommodation', models.TextField()),
                ('transportation', models.TextField()),
                ('overview', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('meta', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('destinations', models.ManyToManyField(to='tour.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=tour.models.tourimagedirectorypath)),
                ('altText', models.CharField(max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
