# Generated by Django 4.1.1 on 2022-12-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourimage',
            old_name='altText',
            new_name='alttag',
        ),
    ]
