# Generated by Django 4.1.1 on 2022-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_imagecaption_postimages_alttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alttag',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
